/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public\scene.gltf 
Author: manoeldarochadeoliveira (https://sketchfab.com/manoeldarochadeoliveira)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/casual-male-architectural-updated-f4e1f9f3463141188281b2212d62a76d
Title: casual male-architectural Updated
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/scene.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="a6b01319cd2d4308903486c20ea7a079fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Rig" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <group name="Object_5">
                    <primitive object={nodes._rootJoint} />
                    <group name="Object_82" scale={0.177} />
                    <skinnedMesh name="Object_83" geometry={nodes.Object_83.geometry} material={materials.Casual_Male} skeleton={nodes.Object_83.skeleton} />
                  </group>
                </group>
                <group name="casual_male001" scale={0.177} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
