/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/Waving.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Waving.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="AuxScene">
        <group name="Waving">
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="Ch24" geometry={nodes.Ch24.geometry} material={materials.Ch24_Body} skeleton={nodes.Ch24.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Waving.gltf')
